apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-frontend
  name: angular-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4200
  selector:
    app: angular-frontend
