apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: deployment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: durga2203/senior-devops-assessment-backend
        name: deployment-backend
        ports:
        - containerPort: 80